# switch panes using Alt-arrow without prefix
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D
bind -n C-.		split-window -h
bind -n M-Enter respawn-pane -k

# disable status bar
set -g status off

# click on a pane to select it
set -g mouse on
set -g history-limit 30000

# make it more responsive
set -s escape-time 50

bind -T copy-mode-vi WheelUpPane send -X scroll-up
bind -T copy-mode-vi WheelDownPane send -X scroll-down

