#!/bin/bash

# ATTENTION !!!
# If the script complains about Android SDK not found, make sure this is in the .bashrc file
#	export ANDROID_HOME=${HOME}/.android-sdk
#	export ANDROID_SDK_ROOT=${ANDROID_HOME}

update_system() {
	echo "Updating and upgrading the system..."
	apt update && apt upgrade -y
	export GPG_TTY=$(tty)
}

update_yadm() {
	yadm remote set-url origin git@github.com:radutomy/dotfiles.git
}

install_packages() {
	apt remove vim* -y
	apt install wget lsb-release libfuse2 bash-completion apt-transport-https \
	build-essential git expect sshpass unzip mosquitto mosquitto-clients \
	dotnet-sdk-8.0 -y
}

repo_sgw() {
	echo "Cloning SGW repo.."
	cd ~ || exit
	git clone --branch dev tktr01@vs-ssh.visualstudio.com:v3/tktr01/TktrDev/device-sgw device-sgw && cd device-sgw
	git config --local user.email "radu.tomuleasa@ticketer.co.uk"
	cd ~
}

#install_rust() {
#  apt install libssl-dev pkg-config build-essential gdb clang rustup -y
#  rustup default stable
#  rustup component add rust-analyzer
#  rustup target add armv7-unknown-linux-musleabihf
#}

install_rust() {
	apt install libssl-dev pkg-config build-essential gdb clang
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path -y
	rustup component add rust-analyzer
	rustup target add armv7-unknown-linux-musleabihf
}

install_helix() {
	add-apt-repository ppa:maveonair/helix-editor -y
	apt install helix -y
}

install_neovim() {
	apt install ripgrep npm python3-venv -y
	curl -L https://github.com/neovim/neovim/releases/download/v0.10.1/nvim.appimage -o /bin/nvim
	chmod +x /bin/nvim
}

install_docker() {
	apt install docker.io docker-buildx docker-compose-v2 -y
}

install_az() {
	curl -sL https://aka.ms/InstallAzureCLIDeb | bash
}

#install_fish() {
#  apt install fish fzf fd-find bat lsd yadm -y
#  # https://github.com/sharkdp/bat/issues/982
#  ln -s /usr/bin/batcat /usr/local/bin/bat
#  fish -c "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher update"
#  chsh -s $(which fish)
#}

install_fish() {
apt install fish fzf fd-find bat yadm -y
	cargo install lsd 
	# https://github.com/sharkdp/bat/issues/982
	ln -s /usr/bin/batcat /usr/local/bin/bat
	fish -c "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher update"
	chsh -s $(which fish)
}

update_system
update_yadm
install_packages
configure_git
repo_sgw
install_rust_temp
install_helix
install_neovim
install_docker
#install_az
install_fish
