#!/bin/bash

update_system() {
	apt update && apt upgrade -y
	export GPG_TTY=$(tty)
	tabs 4 # configure the number of tabs the OS displays
}

update_yadm() {
	yadm remote set-url origin git@github.com:radutomy/dotfiles.git
}

install_packages() {
	apt remove vim* snap* -y
	apt install wget curl yadm lsb-release libfuse2 bash-completion apt-transport-https \
	build-essential git git-delta expect sshpass unzip mosquitto mosquitto-clients \
	dotnet-sdk-8.0 -y
}

repo_sgw() {
	cd ~ || exit
	git clone --branch dev tktr01@vs-ssh.visualstudio.com:v3/tktr01/TktrDev/device-sgw && cd device-sgw
	git config --local user.email "radu.tomuleasa@ticketer.co.uk"
	cd ~

	git clone --branch dev tktr01@vs-ssh.visualstudio.com:v3/tktr01/TktrDev/device-sgw-watcher && cd device-sgw-watcher
	git config --local user.email "radu.tomuleasa@ticketer.co.uk"
	cd ~

	git clone --branch dev tktr01@vs-ssh.visualstudio.com:v3/tktr01/TktrDev/device-sgw-vg1 && cd device-sgw-vg1
	git config --local user.email "radu.tomuleasa@ticketer.co.uk"
	cd ~
}

#install_rust() {
#  apt install libssl-dev libudev-dev pkg-config build-essential gdb clang rustup -y
#  rustup default stable
#  rustup component add rust-analyzer
#  rustup target add armv7-unknown-linux-musleabihf
#}

install_rust() {
	apt install libssl-dev libudev-dev pkg-config build-essential gdb clang -y
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path -y
	$HOME/.cargo/bin/rustup component add rust-analyzer
	$HOME/.cargo/bin/rustup target add armv7-unknown-linux-musleabihf
}

install_helix() {
	add-apt-repository ppa:maveonair/helix-editor -y
	apt install helix -y
}

install_neovim() {
	apt install ripgrep npm python3-venv -y
	curl -L https://github.com/neovim/neovim/releases/download/stable/nvim.appimage -o /bin/nvim
	chmod +x /bin/nvim
	nvim --headless "+Lazy! sync" +qa
	
	# LazyGit
	LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
	curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
	tar xf lazygit.tar.gz lazygit
	install lazygit /usr/local/bin
	rm lazygit*
}

install_docker() {
	apt install docker.io docker-buildx docker-compose-v2 -y
}

install_fish() {
	apt install fish fzf fd-find bat lsd -y
	# https://github.com/sharkdp/bat/issues/982
	ln -s /usr/bin/batcat /usr/local/bin/bat
	fish -c "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher update"
	chsh -s $(which fish)
}

install_az() {
	curl -sL https://aka.ms/InstallAzureCLIDeb | bash
}

cleanup() {
	cd ~
	rm .motd_shown
}

update_system
update_yadm
install_packages
configure_git
repo_sgw
install_rust
install_helix
install_neovim
install_docker
install_fish
#install_az
cleanup
